name: Semgrep

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      # actions/checkout@v4
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Run Semgrep CI
        run: semgrep ci --config p/default
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
